### PR TITLE
Aws profiles or roles

### PR DESCRIPTION
**Pull request by aaron-lane**
This branch enables the use of the [IAM feature added to chef-provisioning-fog](https://github.com/chef/chef-provisioning-fog/issues/80).

@kevindickerson @jtimberman @justindossey

### CODE REVIEW

**Comment by jtimberman** [comment]
Hi there,

There have been a few different folks requesting a more abstract driver configuration capability, and I'm working on adding that. I think it will make this unnecessary.

**Comment by jtimberman** [comment]
That is to say, I'm trying to achieve a greater degree of flexibility and not be tied to AWS implementation details if we don't have to.

**Comment by aaron-lane** [comment]
@jtimberman Indeed, @kevindickerson has already filled me in on your plan, and I give it a hearty :+1:

**Comment by jtimberman** [comment]
@aaron-lane @kevindickerson Please see PR #31.

**Comment by jtimberman** [comment]
I'm fairly sure the direction with PR #31 (now merged) is the right one to get IAM roles usable. My understanding is that you can set the `['chef-server-cluster']['driver']['with-parameter']` to one that uses the IAM role (I'm not sure offhand what that would look like though). Or, set the `['chef-server-cluster']['driver']['gems']` attribute to install chef-provisioning-fog and use the fog IAM user as described [here](https://github.com/chef/chef-provisioning/blob/master/docs/configuration.md#canonical-driver-urls).

**Comment by aaron-lane** [comment]
@jtimberman yeah, #31 looks like the right approach to me, too.

**Comment by jtimberman** [comment]
Cool, I'll close this one. Cheers!

**Pull request closed without merging**
